name:                UrlShortener
version:             0.1.0.0
github:              "githubuser/UrlShortener"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/UrlShortener#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- hedis
- mtl
- network-uri
- random
- scotty
- semigroups
- text
- transformers

extra-deps:
  - text

library:
  source-dirs: src

executables:
  UrlShortener-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UrlShortener

tests:
  UrlShortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UrlShortener
